### ISSUE TITLE
Bug of RequiresRoles(), when logic = AND.

### ISSUE THREAD

**Issue by kuchaguangjie** [maxwellhertz/gin-casbin#4]
In `RequiresRoles()`, when `logic = AND`, the old code use `reflect.DeepEqual()` to check, but when the user has more roles than required, it will fail.

I have created a PR that fixed this issue, using `sort.SearchStrings()`. And it passed my test.
PR Link: https://github.com/maxwellhertz/gin-casbin/pull/3

**Comment by maxwellhertz** [comment]
Ooops... I missed the corner case. Thanks for the fix!
